from pathlib import Path

ACTIVE_BLOCK = r'''    Conqueror:[
      role('Dungeon','Fast-clear S2 dungeon meta',['Flash Fire','Flame Aura','Flickering Blade','Blade Storm'],['Piercing Assault','Tactical Adaptation','Soul Splash','Insightful Eye'],'Flash Fire and Flame Aura provide fast area pressure while Flickering Blade and Blade Storm clean up survivors. High Crit: Insightful Eye → Soul Breaker.','Soul Splash is the default safety slot. Use Indomitable Will if deaths are costing clears, and Aegiswing when you need more survivability.','Current Global meta'),
      role('Crucible / Conquest','Single-target score / raid-boss meta',['Flame Aura','Blade Storm','Flash Fire','Flickering Blade'],['Piercing Assault','Tactical Adaptation','Blazing Clash','Insightful Eye'],'Flame Aura, Blade Storm, Flash Fire, and Flickering Blade maximize sustained single-target pressure. High Crit: Insightful Eye → Crit Mastery.','Prioritize rank and ascension on the four equipped Techniques. Indomitable Will is the safety flex when the boss can kill you.','Prydwen score core'),
      role('Arena','Solo PvP / anti-Guardian pressure',['Darkness Descends','Doom Blade','Flickering Blade','Blade Storm'],['Piercing Assault','Tactical Adaptation','Soul Breaker','Indomitable Will'],'Darkness Descends supplies mobility and Dispel, while Doom Blade, Flickering Blade, and Blade Storm keep pressure high. Low Crit: Soul Breaker → Insightful Eye.','Accuracy is especially valuable against high-Block Guardians. Indomitable Will protects against opening burst.','Current PvP'),
      role('Tournament · 2v2','Duo PvP: sustain + kill pressure',['Darkness Descends','Soul Piercer','Flickering Blade','Blade Storm'],['Piercing Assault','Tactical Adaptation','Soul Breaker','Indomitable Will'],'Soul Piercer adds sustain, Darkness Descends handles mobility and Dispel, and Flickering Blade + Blade Storm provide kill pressure. Low Crit: Soul Breaker → Insightful Eye.','Indomitable Will is core insurance in 2v2. Doom Blade is an offensive flex when your partner already provides enough control.','Current Global PvP'),
      role('Tournament · 4v4','Team PvP: reach, Dispel and coordinated tempo',['Flash Fire','Darkness Descends','Flickering Blade','Blade Storm'],['Insightful Eye','Piercing Assault','Tactical Adaptation','Indomitable Will'],'Flash Fire gives reach, Darkness Descends removes buffs, and Flickering Blade + Blade Storm provide coordinated pressure. With two Conquerors, the higher-rank Gale Dance user can bring it for team SPD.','Indomitable Will protects against focus fire. Insightful Eye → Soul Breaker at high Crit.','Current Global PvP')
    ],
    Guardian:[
      role('Dungeon · Tank','Primary S2 party-tank meta',['Valor Surge','Heart of Challenge','Luminous Shield','Desperate Protection'],['Iron Will','Holy Aegis','Block Awareness','Soul Protection'],'Valor Surge buffs the party, Heart of Challenge controls aggro, and Luminous Shield + Desperate Protection stabilize heavy damage. Need more Taunt: Valor Surge → Hamper Strike.','Iron Will, Holy Aegis, Block Awareness, and Soul Protection form the default survival package. Iron Fortress is the first flex when the whole team needs more mitigation.','Prydwen dungeon core'),
      role('Crucible / Conquest · Tank','Carry-support / boss tank meta',['Valor Surge','Leap Attack','Holy Purification','Lunarwater Threads'],['Frigid Aura','Frigid Glint','Iron Fortress','Oath of Vigil'],'Valor Surge supports the carry, Holy Purification brings Dispel, Leap Attack contributes DEF Down, and Lunarwater Threads adds Water/Cold pressure.','Frigid Aura + Frigid Glint add boss damage while Iron Fortress + Oath of Vigil protect the party. If personal survival is a problem, Frigid Glint → Soul Protection; then Frigid Aura → Holy Aegis.','Guide-backed'),
      role('Arena · Tank','Solo block / reflect wall',['Luminous Shield','Forceful Charge','Star Shattering Slash','Desperate Protection'],['Rebound','Holy Aegis','Block Mastery','Soul Protection'],'Forceful Charge maintains contact and Star Shattering Slash supplies kill pressure while Luminous Shield and Desperate Protection cover burst windows.','Rebound, Holy Aegis, Block Mastery, and Soul Protection reward high Block and punish repeated hits. Low Block: Soul Protection → Block Awareness.','Current PvP'),
      role('Tournament · 2v2 · Tank','Duo frontline: protect one carry and still threaten',['Hamper Strike','Heart of Challenge','Luminous Shield','Desperate Protection'],['Iron Will','Rebound','Iron Fortress','Oath of Vigil'],'Hamper Strike + Heart of Challenge control targeting while Luminous Shield and Desperate Protection protect the frontline.','Oath of Vigil protects your partner; Iron Fortress and Iron Will absorb team pressure. Rebound → Soul Protection if you are being focused too hard.','Current PvP'),
      role('Tournament · 4v4 · Tank','Full-team tank: Taunt + ally protection',['Hamper Strike','Heart of Challenge','Luminous Shield','Desperate Protection'],['Iron Will','Soul Protection','Iron Fortress','Oath of Vigil'],'Hamper Strike + Heart of Challenge provide reliable Taunt, with Luminous Shield and Desperate Protection covering coordinated burst.','Iron Will, Soul Protection, Iron Fortress, and Oath of Vigil maximize team protection and keep the lowest-HP ally safer.','Prydwen + Global PvP'),
      role('Dungeon · DPS','Water AoE / fast-clear bruiser',['Swirling Blade','Lunarwater Threads','Seismic Tide','Raging Maelstrom'],['Frigid Aura','Defensive Assault','Frigid Glint','Potential Rebirth'],'Swirling Blade, Lunarwater Threads, Seismic Tide, and Raging Maelstrom stack Cold and spread Water AoE quickly.','Potential Rebirth covers risky clears. Pursuit of Victory is the damage flex once survivability is comfortable.','Prydwen Water core'),
      role('Crucible / Conquest · DPS','Single-target Guardian score build',['Swirling Blade','Lunarwater Threads','Seismic Tide','Star Shattering Slash'],['Frigid Aura','Defensive Assault','Frigid Glint','Pursuit of Victory'],'Swirling Blade, Lunarwater Threads, and Seismic Tide maintain Cold while Star Shattering Slash delivers the heavy single-target hit.','Frigid Aura, Defensive Assault, Frigid Glint, and Pursuit of Victory maximize the Water/Cold damage package. If Star Shattering Slash is badly under-ranked, compare it with Raging Maelstrom on your account.','Prydwen ST hybrid + Global testing'),
      role('Arena · DPS','Offensive block / counter bruiser',['Swirling Blade','Luminous Shield','Forceful Charge','Star Shattering Slash'],['Rebound','Holy Aegis','Block Mastery','Eye for an Eye'],'Swirling Blade and Forceful Charge keep pressure on the target while Star Shattering Slash supplies the finisher and Luminous Shield preserves bruiser durability.','Rebound, Holy Aegis, Block Mastery, and Eye for an Eye turn Block into counter pressure. Eye for an Eye → Soul Protection or Potential Rebirth if burst is too high.','Prydwen + PvP'),
      role('Tournament · 2v2 · DPS','Duo bruiser: survive focus while threatening kills',['Swirling Blade','Luminous Shield','Forceful Charge','Star Shattering Slash'],['Rebound','Holy Aegis','Block Mastery','Eye for an Eye'],'Swirling Blade, Forceful Charge, and Star Shattering Slash create kill pressure while Luminous Shield helps survive focus.','Rebound, Holy Aegis, and Block Mastery support the bruiser core. Eye for an Eye → Soul Protection when you are the primary focus target.','Current PvP'),
      role('Tournament · 4v4 · DPS','Water AoE team-pressure build',['Swirling Blade','Lunarwater Threads','Seismic Tide','Raging Maelstrom'],['Frigid Aura','Defensive Assault','Frigid Glint','Potential Rebirth'],'Swirling Blade, Lunarwater Threads, Seismic Tide, and Raging Maelstrom spread Cold and Water AoE across the enemy team.','Potential Rebirth is the safety slot. Pursuit of Victory is the damage flex when another frontline is reliably absorbing focus.','Prydwen Water + PvP')
    ],
    Destroyer:[
      role('Dungeon','Fire AoE horde-clear meta',['Formation Breaker','Fiery Star Trail','Fireball','Meteoric Flames'],['Rapid Cast','Void Bubble','Explosive Spirit','Fiery Burst'],'Fiery Star Trail, Fireball, and Meteoric Flames repeatedly trigger Fiery Burst across dense packs, with Formation Breaker improving tempo.','Void Bubble is the default safety slot; an offensive Charm can take its place when survivability is comfortable.','Prydwen + Global testing'),
      role('Crucible / Conquest','Single-target score meta',['Formation Breaker','Divine Wrath','Wind Blade Spiral','Thunder of Judgment'],['Rapid Cast','Mana Surge','Radiant Sear','Incarnation of Light'],'Formation Breaker accelerates the team while Divine Wrath, Wind Blade Spiral, and Thunder of Judgment concentrate boss damage. Wind\'s Delight or Tempest Sphere are rank-dependent flexes for Wind Blade Spiral.','Incarnation of Light favors score; Void Bubble adds safety. Meteoric Flames can outperform Divine Wrath on smaller bosses, so test both if needed.','Guide + score testing'),
      role('Arena','Wind control / solo tempo',['Formation Breaker','Tempest Sphere','Wind Blade Spiral',"Wind's Delight"],['Cyclone Lament','Repelling Wind',"Wind's Shadow",'Void Bubble'],'Formation Breaker accelerates actions while Tempest Sphere, Wind Blade Spiral, and Wind\'s Delight concentrate Wind pressure on a single target.','Void Bubble provides the safety layer; Repelling Wind helps keep melee opponents off you.','Prydwen + Global PvP'),
      role('Tournament · 2v2','Duo control + Formation Breaker tempo',['Formation Breaker','Tempest Sphere','Wind Blade Spiral',"Wind's Delight"],['Rapid Cast','Void Bubble','Repelling Wind','Cyclone Lament'],'Formation Breaker improves duo tempo while Tempest Sphere, Wind Blade Spiral, and Wind\'s Delight apply focused Wind pressure.','Void Bubble provides safety, Repelling Wind controls melee pressure, and Cyclone Lament rewards repeated Wind attacks. Radiant Sear is the damage flex when your teammate already supplies control.','Current PvP'),
      role('Tournament · 4v4','Team AoE + Formation Breaker acceleration',['Formation Breaker','Howling Hurricane','Meteoric Flames','Wind Blade Spiral'],['Rapid Cast','Void Bubble','Cyclone Lament','Radiant Sear'],'Formation Breaker accelerates the team while Howling Hurricane, Meteoric Flames, and Wind Blade Spiral spread AoE and Laceration pressure.','Void Bubble protects against coordinated focus; Cyclone Lament and Radiant Sear turn repeated hits into additional pressure.','Prydwen team core')
    ],
    Dominator:[
      role('Dungeon · DPS','AoE Dark / Erosion clear',['Mana Blast','Dark Bullet','Abyssal Hand','Shadow Impact'],['Shadow Vengeance',"Night's Blessing",'Shadow Erosion','Linked Misfortune'],'Mana Blast, Dark Bullet, Abyssal Hand, and Shadow Impact spread Erosion and direct damage across dungeon packs.','Effect Hit Rate is the key consistency stat for Erosion. Nyxarchon is the default damage Fantomon.','Prydwen AoE core'),
      role('Crucible / Conquest · DPS','Single-target direct / Erosion hybrid',['Dark Bullet','Dark Starburst','Chaos Rune','Shadow of Termination'],['Shadow Vengeance',"Night's Blessing",'Shadow Erosion','Linked Misfortune'],'Dark Starburst + Chaos Rune provide reliable direct damage while Dark Bullet + Shadow of Termination maintain and cash out Erosion. High EHR: Chaos Rune → Mana Blast.','Shadow Vengeance, Night\'s Blessing, Shadow Erosion, and Linked Misfortune maximize personal boss damage. For carry-support teams, Decoy + Frenzy + Mantra is the team-amplification option.','Prydwen ST core'),
      role('Arena · DPS','Single-target Dark pressure',['Dark Bullet','Dark Starburst','Chaos Rune','Shadow of Termination'],['Shadow Vengeance',"Night's Blessing",'Shadow Erosion','Linked Misfortune'],'Dark Bullet, Dark Starburst, Chaos Rune, and Shadow of Termination focus Dark pressure and Erosion on one opponent. High EHR: Chaos Rune → Mana Blast.','Shadow Vengeance provides a survival window while Night\'s Blessing, Shadow Erosion, and Linked Misfortune scale the damage cycle. Use a direct-damage flex if Chaos Rune is badly under-ranked.','Prydwen ST + PvP'),
      role('Tournament · 2v2 · DPS','Duo kill pressure + revive',['Dark Bullet','Dark Starburst','Chaos Rune','Shadow of Termination'],['Shadow Vengeance','Shadow Erosion','Linked Misfortune','Resurrection'],'Dark Bullet, Dark Starburst, Chaos Rune, and Shadow of Termination provide focused kill pressure.','Resurrection can swing the round after a teammate falls, while Shadow Vengeance, Shadow Erosion, and Linked Misfortune preserve damage and survivability.','Prydwen + PvP'),
      role('Tournament · 4v4 · DPS','AoE Dark pressure + revive',['Mana Blast','Dark Bullet','Abyssal Hand','Shadow Impact'],['Shadow Vengeance','Shadow Erosion','Linked Misfortune','Resurrection'],'Mana Blast, Dark Bullet, Abyssal Hand, and Shadow Impact spread Dark/Erosion pressure across multiple targets.','Resurrection adds high-impact team utility while Shadow Vengeance, Shadow Erosion, and Linked Misfortune keep the AoE damage engine active.','Prydwen + PvP'),
      role('Dungeon · Heals','Hard-dungeon healer',['Waterling Summon','Rejuvenating Rain','Radiant Restoration','Frenzy Totem'],['Phantom Light','Healing Mastery','Overhealing','Resurrection'],'Waterling Summon, Rejuvenating Rain, Radiant Restoration, and Frenzy Totem provide steady healing plus team offense. Need more raw healing: Frenzy Totem → Healing Touch.','Phantom Light, Healing Mastery, Overhealing, and Resurrection form the main sustain package. If nobody is dying, Resurrection → Mantra of Blessings.','Prydwen healer core'),
      role('Crucible / Conquest · Heals','Hypercarry support / boss score',['Radiant Restoration','Decoy Clone','Frenzy Totem','Dark Bullet'],['Phantom Light','Healing Mastery','Overhealing','Mantra of Blessings'],'Radiant Restoration covers efficient healing while Decoy Clone, Frenzy Totem, and Dark Bullet support the strongest carry and maintain debuff pressure.','Phantom Light, Healing Mastery, Overhealing, and Mantra of Blessings prioritize support throughput. Decoy positioning matters because only one effective link can attach.','Prydwen + Global support testing'),
      role('Arena · Heals','Specialist sustain hybrid',['Rejuvenating Rain','Radiant Restoration','Dark Bullet','Shadow of Termination'],['Phantom Light','Healing Mastery','Shadow Vengeance','Mantra of Blessings'],'Rejuvenating Rain and Radiant Restoration provide sustain while Dark Bullet and Shadow of Termination keep kill pressure.','Phantom Light and Healing Mastery scale sustain; Shadow Vengeance and Mantra of Blessings preserve tempo and damage. This role works best with strong Healing Boost/SPD gear.','PvP specialist'),
      role('Tournament · 2v2 · Heals','Duo sustain / carry support',['Rejuvenating Rain','Radiant Restoration','Frenzy Totem','Dark Bullet'],['Phantom Light','Healing Mastery','Resurrection','Shadow Vengeance'],'Rejuvenating Rain and Radiant Restoration keep your partner stable while Frenzy Totem boosts output and Dark Bullet maintains pressure.','Resurrection is the key swing utility; Phantom Light and Healing Mastery raise sustain while Shadow Vengeance protects your own damage window.','PvP support'),
      role('Tournament · 4v4 · Heals','Hybrid team support',['Radiant Restoration','Decoy Clone','Frenzy Totem','Dark Bullet'],['Phantom Light','Healing Mastery','Resurrection','Mantra of Blessings'],'Radiant Restoration, Decoy Clone, and Frenzy Totem support the team while Dark Bullet maintains debuff pressure.','Phantom Light, Healing Mastery, Resurrection, and Mantra of Blessings balance healing, revive utility, and team damage.','Team PvP')
    ]'''

TARGETS = [Path('index.html'), Path('.github/build-fantomons-inject.html')] + sorted(Path('scripts').glob('*.py')) + sorted(Path('.github').glob('*.py'))
changed = []
for path in TARGETS:
    if not path.exists() or path.name == Path(__file__).name:
        continue
    text = path.read_text(encoding='utf-8')
    start = text.find('    Conqueror:[')
    if start < 0:
        continue
    end_marker = '\n  };\n\n  const FANTO={'
    end = text.find(end_marker, start)
    if end < 0:
        continue
    new_text = text[:start] + ACTIVE_BLOCK + text[end:]
    if new_text != text:
        path.write_text(new_text, encoding='utf-8')
        changed.append(str(path))

policy = Path('.github/build-maintenance.md')
if policy.exists():
    text = policy.read_text(encoding='utf-8')
    rule = '- **Build-card notes must read as standalone player guidance.** Describe why the equipped loadout works and give only useful optional swaps; do not narrate a previous version of the build (for example, “drop X,” “use Y instead,” “this card,” or other change-log/editorial commentary).\n'
    anchor = '- Each loadout must show exactly 4 Techniques and 4 Charms actually equipped, plus concise swaps/conditions where useful.\n'
    if rule not in text:
        if anchor not in text:
            raise SystemExit('maintenance policy anchor missing')
        text = text.replace(anchor, anchor + rule)
        policy.write_text(text, encoding='utf-8')
        changed.append(str(policy))

if '.github/build-fantomons-inject.html' not in changed or 'index.html' not in changed:
    raise SystemExit(f'expected runtime files were not both updated: {changed}')
print('updated:', ', '.join(changed))
