from pathlib import Path

paths = [Path('index.html'), Path('.github/build-fantomons-inject.html')]

old_css = '''.buildCard .fantomonPair{border-top:1px solid var(--line);margin-top:14px;padding-top:12px}\n.buildCard .fantomonPair>span{color:var(--muted);letter-spacing:.08em;text-transform:uppercase;margin-bottom:7px;font-size:9px;font-weight:850;display:block}\n.buildCard .fantomonPairNote{color:var(--muted);font-size:8px;line-height:1.35;margin:-2px 0 7px}\n.buildCard .fantomonRankList{display:grid;grid-template-columns:1fr 1fr;gap:7px}\n.buildCard .fantomonPick{border:1px solid var(--line);background:color-mix(in srgb,var(--surface) 88%,var(--accent-strong) 12%);border-radius:9px;padding:8px 9px;min-width:0}\n.buildCard .fantomonPick small{color:var(--muted);display:block;font-size:8px;font-weight:850;letter-spacing:.08em;text-transform:uppercase;margin-bottom:2px}\n.buildCard .fantomonPick b{color:var(--ink);display:block;font-size:10px;line-height:1.3}\n.buildCard .fantomonPick p{color:var(--muted);font-size:9px;line-height:1.35;margin:4px 0 0}\n.buildCard .fantomonPick.main{border-color:color-mix(in srgb,var(--accent-strong) 48%,var(--line))}\n'''
new_css = '''.buildCard .buildLoadoutColumn{min-width:0;display:grid;grid-template-columns:1fr;gap:13px;align-content:start}\n.buildCard .fantomonPair{border-top:1px solid var(--line);margin-top:14px;padding-top:12px;min-width:0}\n.buildCard .fantomonPair>span{color:var(--muted);letter-spacing:.08em;text-transform:uppercase;margin-bottom:8px;font-size:9px;font-weight:850;display:block}\n.buildCard .fantomonPairNote{color:var(--muted);font-size:8px;line-height:1.35;margin:-2px 0 7px}\n.buildCard .fantomonRankList{display:grid;grid-template-columns:1fr;gap:7px}\n.buildCard .fantomonPick{border:1px solid var(--line);background:color-mix(in srgb,var(--surface) 88%,var(--accent-strong) 12%);border-radius:9px;padding:9px 10px;min-width:0}\n.buildCard .fantomonPick small{color:var(--muted);display:block;font-size:8px;font-weight:850;letter-spacing:.08em;text-transform:uppercase;margin-bottom:3px}\n.buildCard .fantomonPick b{color:var(--ink);display:block;font-size:10px;line-height:1.3}\n.buildCard .fantomonPick p{color:var(--muted);font-size:9.5px;line-height:1.4;margin:4px 0 0}\n.buildCard .fantomonPick.main{border-color:color-mix(in srgb,var(--accent-strong) 48%,var(--line))}\n'''

old_meta = '''@media(min-width:761px){\n  .builds .buildGrid.metaModeGrid>.buildCard:not([hidden]){display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);column-gap:18px;align-items:start}\n  .builds .buildGrid.metaModeGrid>.buildCard:not([hidden])>header,\n  .builds .buildGrid.metaModeGrid>.buildCard:not([hidden])>.fantomonPair{grid-column:1/-1}\n}\n'''
new_meta = '''@media(min-width:761px){\n  .builds .buildGrid.metaModeGrid>.buildCard:not([hidden]){display:grid;grid-template-columns:minmax(0,1.08fr) minmax(340px,.92fr);column-gap:18px;row-gap:0;align-items:start}\n  .builds .buildGrid.metaModeGrid>.buildCard:not([hidden])>header{grid-column:1/-1}\n  .builds .buildGrid.metaModeGrid>.buildCard:not([hidden])>.buildLoadoutColumn{grid-column:1;grid-row:2}\n  .builds .buildGrid.metaModeGrid>.buildCard:not([hidden])>.fantomonPair{grid-column:2;grid-row:2;border-top:0;border-left:1px solid var(--line);margin-top:0;padding:0 0 0 18px;align-self:start}\n}\n@media(max-width:760px){\n  .builds .buildGrid.metaModeGrid>.buildCard:not([hidden])>.buildLoadoutColumn,\n  .builds .buildGrid.metaModeGrid>.buildCard:not([hidden])>.fantomonPair{grid-column:1/-1}\n  .builds .buildGrid.metaModeGrid>.buildCard:not([hidden])>.fantomonPair{border-left:0;border-top:1px solid var(--line);margin-top:14px;padding:12px 0 0}\n}\n'''

old_render = '''    return '<article class="buildCard" data-role="'+esc(displayName)+'"'+roleAttr+'>'\n      +'<header><div><h3>'+esc(displayName)+'<span class="roleBadge">'+esc(r.confidence)+'</span></h3><p>'+esc(r.subtitle)+'</p></div></header>'\n      +'<div class="skillGroup"><span>Techniques</span><div>'+r.techniques.map(x=>'<b>'+esc(x)+'</b>').join('')+'</div></div>'\n      +'<div class="skillGroup"><span>Charms</span><div>'+r.charms.map(x=>'<b>'+esc(x)+'</b>').join('')+'</div></div>'\n      +((techniqueSwaps.length||charmSwaps.length)?'<div class="buildSwapRows">'\n        +techniqueSwaps.map(s=>'<p><strong>Technique Swap:</strong><span class="swapText">'+esc(s[0])+' — <span class="swapNames">'+esc(s[1])+' → '+esc(s[2])+'</span></span></p>').join('')\n        +charmSwaps.map(s=>'<p><strong>Charm Swap:</strong><span class="swapText">'+esc(s[0])+' — <span class="swapNames">'+esc(s[1])+' → '+esc(s[2])+'</span></span></p>').join('')\n        +'</div>':'')\n      +'</article>';\n'''
new_render = '''    return '<article class="buildCard" data-role="'+esc(displayName)+'"'+roleAttr+'>'\n      +'<header><div><h3>'+esc(displayName)+'<span class="roleBadge">'+esc(r.confidence)+'</span></h3><p>'+esc(r.subtitle)+'</p></div></header>'\n      +'<div class="buildLoadoutColumn">'\n        +'<div class="skillGroup"><span>Techniques</span><div>'+r.techniques.map(x=>'<b>'+esc(x)+'</b>').join('')+'</div></div>'\n        +'<div class="skillGroup"><span>Charms</span><div>'+r.charms.map(x=>'<b>'+esc(x)+'</b>').join('')+'</div></div>'\n        +((techniqueSwaps.length||charmSwaps.length)?'<div class="buildSwapRows">'\n          +techniqueSwaps.map(s=>'<p><strong>Technique Swap:</strong><span class="swapText">'+esc(s[0])+' — <span class="swapNames">'+esc(s[1])+' → '+esc(s[2])+'</span></span></p>').join('')\n          +charmSwaps.map(s=>'<p><strong>Charm Swap:</strong><span class="swapText">'+esc(s[0])+' — <span class="swapNames">'+esc(s[1])+' → '+esc(s[2])+'</span></span></p>').join('')\n          +'</div>':'')\n      +'</div>'\n      +'</article>';\n'''

old_apply = '''      const pair=picks.slice(0,2);\n      box.innerHTML='<span>Combat Fantomons</span>'\n        +'<div class="fantomonRankList">'\n        +pair.map((p,i)=>'<div class="fantomonPick'+(i===0?' main':'')+'"><small>'+(i===0?'Main':'Alt')+'</small><b>'+esc(p.name)+'</b><p>'+esc(p.why)+'</p></div>').join('')\n        +'</div>';\n'''
new_apply = '''      const pair=picks.slice(0,2);\n      const noShop=f2pFantomon(picks,pair);\n      const shown=noShop?[...pair,noShop]:pair;\n      const labels=['Main','Alt','F2P / No Shop'];\n      box.innerHTML='<span>Combat Fantomons</span>'\n        +'<div class="fantomonRankList">'\n        +shown.map((p,i)=>'<div class="fantomonPick'+(i===0?' main':'')+'"><small>'+labels[i]+'</small><b>'+esc(p.name)+'</b><p>'+esc(p.why)+'</p></div>').join('')\n        +'</div>';\n'''
helper_anchor = '''  function applyFantos(cls){\n'''
helper = '''  // Current S2 direct shop Fantomons. Keep F2P / No Shop eligible for every other acquisition source.\n  const SHOP_SOURCE_FANTOMONS=new Set(['Aegiswing','Nyxarchon']);\n  function f2pFantomon(picks,pair){\n    const used=new Set(pair.map(p=>p.name));\n    return picks.find(p=>!SHOP_SOURCE_FANTOMONS.has(p.name)&&!used.has(p.name))\n      ||picks.find(p=>!SHOP_SOURCE_FANTOMONS.has(p.name))\n      ||null;\n  }\n\n'''

# Dominator Tournament currently has only two ranked choices; add a third non-shop option.
old_dom_tour = "Tournament:[pick('Nyxarchon','Main hybrid Tournament pick: adds real damage and DEF shred while the Dominator handles buffs and utility.'),pick('Terragon','Alt team-utility pick when reducing enemy ATK/pressure matters more than personal damage.')],"
new_dom_tour = "Tournament:[pick('Nyxarchon','Main hybrid Tournament pick: adds real damage and DEF shred while the Dominator handles buffs and utility.'),pick('Terragon','Alt team-utility pick when reducing enemy ATK/pressure matters more than personal damage.'),pick('Sylvaerie','No-shop alternative: ATK + SPD improves both pressure and support tempo.')],"

for path in paths:
    text = path.read_text(encoding='utf-8')
    for old,new in [(old_css,new_css),(old_meta,new_meta),(old_render,new_render),(old_apply,new_apply),(old_dom_tour,new_dom_tour)]:
        if text.count(old)!=1:
            raise SystemExit(f'{path}: expected one match, got {text.count(old)} for block starting {old[:60]!r}')
        text=text.replace(old,new,1)
    if text.count(helper_anchor)!=1:
        raise SystemExit(f'{path}: applyFantos anchor match count {text.count(helper_anchor)}')
    text=text.replace(helper_anchor,helper+helper_anchor,1)
    path.write_text(text,encoding='utf-8')

smoke=Path('scripts/site_smoke_test.mjs')
text=smoke.read_text(encoding='utf-8')
text=text.replace('loadouts, and Main+Alt Fantomon cards. Lock all of that in so it cannot silently', 'loadouts, and Main+Alt+F2P Fantomon cards. Lock all of that in so it cannot silently',1)
old='''  assert(await visibleCards.locator('.fantomonPair').count()===1, `${cls} visible build is missing its Fantomon pair`);\n  const badFanto=await visibleCards.locator('.fantomonPair').evaluateAll(xs=>xs.filter(x=>x.querySelectorAll('.fantomonPick').length!==2).length);\n  assert(badFanto===0, `${cls} visible build does not have exactly Main + Alt Fantomons`);\n'''
new='''  assert(await visibleCards.locator('.fantomonPair').count()===1, `${cls} visible build is missing its Fantomon choices`);\n  const badFanto=await visibleCards.locator('.fantomonPair').evaluateAll(xs=>xs.filter(x=>x.querySelectorAll('.fantomonPick').length!==3).length);\n  assert(badFanto===0, `${cls} visible build does not have exactly Main + Alt + F2P Fantomons`);\n  const f2pLabels=await visibleCards.locator('.fantomonPick small').allTextContents();\n  assert(f2pLabels.some(x=>/F2P \/ No Shop/i.test(x)), `${cls} visible build is missing the F2P / No Shop Fantomon label`);\n  const f2pName=await visibleCards.locator('.fantomonPick').nth(2).locator('b').innerText();\n  assert(!['Nyxarchon','Aegiswing'].includes(f2pName.trim()), `${cls} F2P / No Shop pick incorrectly uses shop Fantomon ${f2pName}`);\n  const cardCols=await visibleCards.evaluate(el=>{const left=el.querySelector('.buildLoadoutColumn')?.getBoundingClientRect();const right=el.querySelector('.fantomonPair')?.getBoundingClientRect();return left&&right?{lx:left.x,ly:left.y,rx:right.x,ry:right.y}:null;});\n  assert(cardCols && cardCols.rx>cardCols.lx+20 && Math.abs(cardCols.ry-cardCols.ly)<30, `${cls} desktop loadout/Fantomon columns are not side-by-side`);\n'''
if text.count(old)!=1:
    raise SystemExit(f'smoke old Fantomon assertion match count {text.count(old)}')
text=text.replace(old,new,1)
old_mobile='''const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);\nassert(overflow<=3, `mobile page has ${overflow}px horizontal overflow`);\n'''
new_mobile='''const mobileBuild=page.locator('#buildContent .buildGrid .buildCard:visible').first();\nconst mobileBuildCols=await mobileBuild.evaluate(el=>{const left=el.querySelector('.buildLoadoutColumn')?.getBoundingClientRect();const right=el.querySelector('.fantomonPair')?.getBoundingClientRect();return left&&right?{lx:left.x,ly:left.y,rx:right.x,ry:right.y}:null;});\nassert(mobileBuildCols && mobileBuildCols.ry>mobileBuildCols.ly && Math.abs(mobileBuildCols.rx-mobileBuildCols.lx)<5, 'mobile Fantomon column did not stack below loadout column');\nconst overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);\nassert(overflow<=3, `mobile page has ${overflow}px horizontal overflow`);\n'''
if text.count(old_mobile)!=1:
    raise SystemExit(f'smoke mobile anchor match count {text.count(old_mobile)}')
text=text.replace(old_mobile,new_mobile,1)
text=text.replace('Fantomon pairs + Dominator roles/PvP refs + mobile stack', 'Main/Alt/F2P Fantomons + Dominator roles/PvP refs + mobile stack',1)
smoke.write_text(text,encoding='utf-8')

print('applied two-column build cards and corrected F2P/no-shop Fantomon slot')
