from pathlib import Path

p = Path('index.html')
s = p.read_text(encoding='utf-8')
old1 = "    ['2026-09-05',53,'Event','Server Tournament · Nexus qualifier','UNCONFIRMED Charming Glance projection. Community reports from older Global servers say the top 4 teams from each server Tournament qualify for the cross-server Nexus Tournament, and a July Nexus field was described as 16 teams made from the top 4 of four servers from the previous day’s server Tournament. If Charming Glance follows that cadence, the likely qualifier window is Sat Sep 5. No official Charming Glance registration or battle time has been posted yet.','event',null,'unconfirmed'],"
new1 = "    ['2026-09-12',60,'Event','Server Tournament · Nexus qualifier','UNCONFIRMED Charming Glance projection, revised after a deeper cadence check. Multiple older-Global player reports agree that only the top 4 teams from each normal server Tournament qualify for Nexus; one observed Nexus bracket had 16 teams, described as the top 4 from each of four servers from the previous day’s Tournament. A separate S2 timing thread says the first Nexus is the SECOND weekend after S2 begins, so for Charming Glance the best current qualifier projection is Sat Sep 12 rather than Sep 5. No official Charming Glance registration or battle time has been posted yet.','event',null,'unconfirmed'],"
old2 = "    ['2026-09-06',54,'Event','Nexus Tournament · 4v4','UNCONFIRMED Charming Glance projection. Current community evidence says Nexus 4v4 begins only after Season 2, with players on older servers describing the first S2 Nexus as the second weekend after S2 / the following Sunday. With Charming Glance entering S2 on Sun Aug 30, the best current projection is Sun Sep 6, likely following a server Tournament qualifier the previous day. Exact registration, preparation, prediction and battle times remain unconfirmed; community reports say the prediction window does not open until the bracket reaches the final four and may last only about 5 minutes. Top 4 server Tournament teams are reported to qualify.','event',null,'unconfirmed'],"
new2 = "    ['2026-09-13',61,'Event','Nexus Tournament · 4v4','UNCONFIRMED Charming Glance projection, revised after a deeper cadence check. Older-Global S2 players explicitly describe the first Nexus as the SECOND weekend after Season 2 starts and as a Sunday event; with Charming Glance entering S2 on Sun Aug 30, that maps more naturally to Sun Sep 13, following the projected Sep 12 server Tournament qualifier. Qualification is strongly community-corroborated as top 4 teams from each server Tournament; an observed bracket had 16 teams from four servers. Event-details screenshots/discussion report only a ~5-minute prediction window, which appears to open once the bracket reaches the final four rather than at a fixed clock time. Community reward reports say participating/placing teams earn Honor Medal currency for the Nexus cosmetic shop; top 32 are reported to receive some medals, while the winning team receives the full cosmetic set temporarily for 7 days. Exact Charming Glance preparation, prediction and battle times remain unconfirmed.','event',null,'unconfirmed'],"
if old1 not in s:
    raise SystemExit('old qualifier row not found')
if old2 not in s:
    raise SystemExit('old nexus row not found')
s = s.replace(old1, new1, 1).replace(old2, new2, 1)
p.write_text(s, encoding='utf-8')
print('NEXUS_4V4_DEEP_DIVE_V2')
