from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')

panels={
'Paladin': r'''      <div class="priorityPanel"><div class="priorityIntro"><span>Core technique investment</span><strong>Star Shattering Slash first</strong><p>Prioritize techniques that are actually used in the Season 1 Paladin builds below. Tank/support utility stays valuable, but the T3 nuke is the biggest new power spike.</p></div><ol class="priorityList"><li><b>1</b><div><strong>Star Shattering Slash</strong><p>Paladin's signature T3 single-target nuke; useful for pushing PvE, Dragon and PvP.</p></div></li><li><b>2</b><div><strong>Heart of Challenge</strong><p>Appears across the listed Paladin setups and anchors the class's control/tank loop.</p></div></li><li><b>3</b><div><strong>Luminous Shield</strong><p>Core survival tool in dungeon and generic PvE builds; directly improves the Block-focused game plan.</p></div></li><li><b>4</b><div><strong>Lunarwater Threads</strong><p>Wide Water AoE with pull utility; key to the Water setup and a strong damage/utility swap in dungeons.</p></div></li></ol></div>
      <div class="priorityPanel"><div class="priorityIntro"><span>Core charm investment</span><strong>Block Mastery first</strong><p>Paladin's T3 charm priorities are still defense-first. Water-specific damage charms come after the Block core unless you are deliberately building the offensive variant.</p></div><ol class="priorityList"><li><b>1</b><div><strong>Block Mastery</strong><p>The standout T3 Paladin charm: directly raises Block Efficiency and scales the class's main defensive mechanic.</p></div></li><li><b>2</b><div><strong>Block Awareness</strong><p>More Block Rate and equipped in the default dungeon and generic PvE builds.</p></div></li><li><b>3</b><div><strong>Iron Fortress</strong><p>High-value dungeon/tank investment when your main job is keeping the party alive.</p></div></li><li><b>4</b><div><strong>Defensive Assault / Rebound</strong><p>Choose by build: Defensive Assault for Water/offense while shielded; Rebound for the generic counter setup.</p></div></li></ol></div>
''',
'Archmage': r'''      <div class="priorityPanel"><div class="priorityIntro"><span>Core technique investment</span><strong>Meteoric Flames + Hurricane</strong><p>These priorities favor techniques that remain equipped across both listed T3 Archmage loadouts, then the encounter-specific finishers.</p></div><ol class="priorityList"><li><b>1</b><div><strong>Meteoric Flames</strong><p>Excellent Fire damage and persistent ground pressure; equipped in both AoE and single-target builds.</p></div></li><li><b>2</b><div><strong>Howling Hurricane</strong><p>Large AoE, strong damage and another universal slot across the standard T3 builds.</p></div></li><li><b>3</b><div><strong>Divine Wrath</strong><p>Exceptional against large single targets and still useful in mixed groups, though its hit pattern can be inconsistent on small targets.</p></div></li><li><b>4</b><div><strong>Wind's Delight / Lightning Chain</strong><p>Use Wind's Delight for single-target consistency and Lightning Chain when AoE coverage matters more.</p></div></li></ol></div>
      <div class="priorityPanel"><div class="priorityIntro"><span>Core charm investment</span><strong>Rapid Cast is mandatory</strong><p>The standard T3 Archmage charm package barely changes between AoE and boss builds, which makes these upgrades unusually safe.</p></div><ol class="priorityList"><li><b>1</b><div><strong>Rapid Cast</strong><p>Very hard to replace: adds Elemental Mastery and lets key techniques come online a turn earlier.</p></div></li><li><b>2</b><div><strong>Radiant Sear</strong><p>The strongest pure damage charm in the T3 Archmage kit and a core proc in both listed builds.</p></div></li><li><b>3</b><div><strong>Void Bubble</strong><p>Universal survival insurance for a glass-cannon class and equipped in both standard setups.</p></div></li><li><b>4</b><div><strong>Mana Surge</strong><p>Reliable Crit support in both builds; this is the first core slot to flex into Lightning Mystery, Elemental Harmony or Repelling Wind.</p></div></li></ol></div>
''',
'Arcanist': r'''      <div class="priorityPanel"><div class="priorityIntro"><span>DPS technique investment</span><strong>Erosion engine first</strong><p>These priorities cover the Dark DoT loadouts. If you mainly heal, prioritize Radiant Restoration and Frenzy Totem instead of forcing the DPS order.</p></div><ol class="priorityList"><li><b>1</b><div><strong>Mana Blast</strong><p>AoE Dark damage with an Erosion chance and a core slot in both the single-target and AoE builds.</p></div></li><li><b>2</b><div><strong>Dark Bullet</strong><p>Reliable single-target Erosion application and equipped in both standard DPS setups.</p></div></li><li><b>3</b><div><strong>Abyssal Hand</strong><p>Reusable Dark AoE plus Slow utility; another shared slot across both DPS builds.</p></div></li><li><b>4</b><div><strong>Shadow of Termination / Shadow Impact</strong><p>Termination cashes out all Erosion on bosses; Shadow Impact is the AoE version that immediately triggers Erosion stacks.</p></div></li></ol></div>
      <div class="priorityPanel"><div class="priorityIntro"><span>DPS charm investment</span><strong>Stack Erosion faster</strong><p>All four charms below are equipped in both standard Arcanist DPS builds. Healers should instead invest in Healing Mastery, Overhealing and Resurrection as needed.</p></div><ol class="priorityList"><li><b>1</b><div><strong>Shadow Erosion</strong><p>Dark Technique hits can apply additional Erosion, making it the foundation of the T3 DoT engine.</p></div></li><li><b>2</b><div><strong>Linked Misfortune</strong><p>Each Erosion application can immediately add another stack, accelerating both sustained damage and burst cash-outs.</p></div></li><li><b>3</b><div><strong>Night's Blessing</strong><p>Straight Dark damage scaling that benefits the entire DPS package.</p></div></li><li><b>4</b><div><strong>Shadow Vengeance</strong><p>Cheat-death plus a one-turn Shadow Form burst window; especially valuable in PvP and difficult progression.</p></div></li></ol></div>
'''
}

for cls,html in panels.items():
    marker=f"if(cls==='{cls}') return `"
    start=s.find(marker)
    if start<0:
        raise SystemExit(f'{cls} block not found')
    # stay inside this class block; find the first build grid after the class header
    grid=s.find('      <div class="buildGrid">', start)
    if grid<0:
        raise SystemExit(f'{cls} buildGrid not found')
    # skip if this class already has a priority panel before its build grid
    if 'priorityPanel' in s[start:grid]:
        continue
    s=s[:grid]+html+s[grid:]

p.write_text(s,encoding='utf-8')
