import {build} from 'esbuild';
import postcss from 'postcss';
import {readFileSync,writeFileSync} from 'node:fs';
const check=process.argv.includes('--check');
function emit(file,text){
 if(check){if(readFileSync(file,'utf8').replaceAll('\r\n','\n')!==text.replaceAll('\r\n','\n'))throw new Error(`${file} is stale: run npm run build`);}
 else writeFileSync(file,text);
}
const bundle=await build({entryPoints:['src/app.mjs'],bundle:true,format:'iife',target:'es2020',write:false,legalComments:'none',charset:'utf8',banner:{js:'// Generated by npm run build. Edit src/*.mjs instead.'}});
emit('assets/runtime.js',bundle.outputFiles[0].text);
const root=postcss.root();
for(const file of ['legacy','calculator','shared'])root.append(postcss.parse(readFileSync(`src/styles/${file}.css`,'utf8'),{from:`src/styles/${file}.css`}).nodes);
// Remove earlier declarations only for the identical selector, property, priority
// and enclosing conditions. Do not merge selectors or move rules across the cascade.
const seen=new Set();let removed=0;
const rules=[];root.walkRules(rule=>rules.push(rule));
for(const rule of rules.reverse()){
 const scope=[];let parent=rule.parent;
 while(parent&&parent.type!=='root'){scope.unshift([parent.name,parent.params]);parent=parent.parent;}
 if(scope.some(([name])=>name?.includes('keyframes')))continue;
 // Keep fallback declarations within each rule intact.
 const local=new Set();
 for(const d of [...rule.nodes].reverse()){
  if(d.type!=='decl')continue;
  const key=JSON.stringify([scope,rule.selector,d.prop,d.important||false]);
  if(seen.has(key)){d.remove();removed++;}else local.add(key);
 }
 for(const key of local)seen.add(key);
 if(!rule.nodes.length)rule.remove();
}
root.walkComments(c=>c.remove());
// Whitespace-only serialization; values and selector whitespace stay intact.
root.walk(node=>{node.raws.before='';node.raws.between=node.type==='decl'?':':'';node.raws.after='';if(node.type==='decl')node.raws.important=node.important?'!important':undefined;});
root.raws.after='';
emit('assets/site.css',root.toString()+'\n');
console.log(`Assets ${check?'verified':'built'}; ${removed} superseded CSS declarations removed.`);
