from pathlib import Path
import re

p = Path('scripts/patch_guardian_tank_dps_toggle_v1.py')
s = p.read_text(encoding='utf-8')

new_func = r'''def patch_meta_source(text: str) -> str:
    text = replace_guardian_block_meta_source(text)

    # Patch the META_CSS raw string carried by the maintained meta installer.
    if MARK not in text:
        css_anchor = '/* META_BUILD_MODES_V1 */\n.builds .metaBuildControls'
        if css_anchor not in text:
            raise RuntimeError('Could not locate META_BUILD_MODES CSS anchor in meta source')
        text = text.replace(css_anchor, '/* META_BUILD_MODES_V1 */\n' + GUARDIAN_CSS + '.builds .metaBuildControls', 1)

    # Patch the META_JS raw string carried by the maintained meta installer.
    if 'const guardianBuildMode=' not in text:
        anchor = "  const metaTournamentSize=()=>metaRead('sxs-build-tournament-size','4v4')==='2v2'?'2v2':'4v4';\n"
        if anchor not in text:
            raise RuntimeError('Could not find meta tournament-size anchor in meta source')
        text = text.replace(anchor, anchor + GUARDIAN_META_JS, 1)

    old = "    if(!grid) return;\n    let box=document.querySelector('.builds .metaBuildControls');"
    new = "    if(!grid) return;\n    ensureGuardianRoleControl(cls);\n    let box=document.querySelector('.builds .metaBuildControls');"
    if old in text:
        text = text.replace(old, new, 1)

    if "const mode=metaMode(), size=metaTournamentSize(), guardianMode=guardianBuildMode();" not in text:
        old = "    const mode=metaMode(), size=metaTournamentSize();\n"
        new = "    const mode=metaMode(), size=metaTournamentSize(), guardianMode=guardianBuildMode();\n    document.querySelectorAll('.builds .guardianModeTabs [data-guardian-mode]').forEach(b=>{const on=b.dataset.guardianMode===guardianMode;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});\n"
        if old not in text:
            raise RuntimeError('Could not patch meta visibility declaration in meta source')
        text = text.replace(old, new, 1)

    old = "    grid.querySelectorAll(':scope > .buildCard').forEach(card=>{card.hidden=card.dataset.role!==wanted;});\n"
    new = "    grid.querySelectorAll(':scope > .buildCard').forEach(card=>{\n      const wrongActivity=card.dataset.role!==wanted;\n      const wrongGuardianRole=cls==='Guardian'&&card.dataset.guardianRole!==guardianMode;\n      card.hidden=wrongActivity||wrongGuardianRole;\n    });\n"
    if old in text:
        text = text.replace(old, new, 1)

    # The click handler is generated by patch_inject() rather than living in META_JS.
    if "const guardianBtn=e.target.closest?.('[data-guardian-mode]');" not in text:
        old = "    new = old + \"\\n    root?.addEventListener('click',e=>{\\n      const modeBtn=e.target.closest?.('[data-meta-mode]');\\n      if(modeBtn){metaWrite('sxs-build-meta-mode',modeBtn.dataset.metaMode);applyMetaVisibility(activeClass());return;}\\n      const sizeBtn=e.target.closest?.('[data-tournament-size]');\\n      if(sizeBtn){metaWrite('sxs-build-tournament-size',sizeBtn.dataset.tournamentSize);applyMetaVisibility(activeClass());}\\n    });\""
        new = "    new = old + \"\\n    root?.addEventListener('click',e=>{\\n      const guardianBtn=e.target.closest?.('[data-guardian-mode]');\\n      if(guardianBtn&&activeClass()==='Guardian'){metaWrite('sxs-build-guardian-mode',guardianBtn.dataset.guardianMode==='dps'?'dps':'tank');applyMetaVisibility('Guardian');queueApply();return;}\\n      const modeBtn=e.target.closest?.('[data-meta-mode]');\\n      if(modeBtn){metaWrite('sxs-build-meta-mode',modeBtn.dataset.metaMode);applyMetaVisibility(activeClass());return;}\\n      const sizeBtn=e.target.closest?.('[data-tournament-size]');\\n      if(sizeBtn){metaWrite('sxs-build-tournament-size',sizeBtn.dataset.tournamentSize);applyMetaVisibility(activeClass());}\\n    });\""
        if old not in text:
            raise RuntimeError('Could not patch generated click handler in meta source')
        text = text.replace(old, new, 1)

    if 'GUARDIAN_ROLE_TOGGLE_V1' not in text or 'data-guardian-mode' not in text:
        raise RuntimeError('Guardian meta source patch incomplete')
    return text
'''

pat = re.compile(r'def patch_meta_source\(text: str\) -> str:\n.*?\n\ndef patch_rich', re.S)
s, n = pat.subn(new_func + '\n\ndef patch_rich', s, count=1)
if n != 1:
    raise SystemExit('Could not replace patch_meta_source in Guardian toggle patch')
p.write_text(s, encoding='utf-8')
print('Fixed Guardian toggle meta-source patching')
