from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')

old_block="""    ['2026-09-12',60,'Event','Server Tournament · Nexus qualifier','UNCONFIRMED Charming Glance projection, revised after a deeper cadence check. Multiple older-Global player reports agree that only the top 4 teams from each normal server Tournament qualify for Nexus; one observed Nexus bracket had 16 teams, described as the top 4 from each of four servers from the previous day’s Tournament. A separate S2 timing thread says the first Nexus is the SECOND weekend after S2 begins, so for Charming Glance the best current qualifier projection is Sat Sep 12 rather than Sep 5. No official Charming Glance registration or battle time has been posted yet.','event',null,'unconfirmed'],
    ['2026-09-13',61,'Event','Nexus Tournament · 4v4','STRONGLY SUPPORTED / UNCONFIRMED FOR CHARMING GLANCE. Multiple older-Global reports place Nexus on Sundays, and a player-provided older-server calendar independently shows Nexus 4v4 on Aug. 30 and Sep. 13 exactly 14 days apart. That calendar’s other S2 season-day milestones (Bladeshire Day 40, Pandarial Day 46, Celestship Day 53, season end Day 67) match the established roadmap, increasing confidence that Nexus follows a biweekly Sunday cadence after a server becomes eligible. Community reports also say the first Nexus is the second weekend after S2 begins; with Charming Glance entering S2 on Sun Aug. 30, Sep. 13 remains the best first-event projection. Top 4 teams from each server Tournament qualify; one observed bracket had 16 teams from four servers. Prediction appears to open for only about 5 minutes once the bracket reaches the final four. Exact Charming Glance battle time remains unconfirmed.','event',null,'unconfirmed'],
    ['2026-09-26',74,'Event','Server Tournament · Nexus qualifier','UNCONFIRMED recurring projection. If the newly corroborated 14-day Sunday Nexus cadence holds for Charming Glance, the next server Tournament qualifier should occur the preceding Saturday, Sep. 26. Qualification format is community-corroborated as top 4 teams advancing to Nexus.','event',null,'unconfirmed'],
    ['2026-09-27',75,'Event','Nexus Tournament · 4v4','UNCONFIRMED recurring projection from the older-server biweekly Sunday cadence: two weeks after the projected Sep. 13 Charming Glance Nexus.','event',null,'unconfirmed'],
    ['2026-10-10',88,'Event','Server Tournament · Nexus qualifier','UNCONFIRMED recurring projection. If the biweekly Nexus cadence continues unchanged, the qualifying server Tournament should be the preceding Saturday, Oct. 10.','event',null,'unconfirmed'],
    ['2026-10-11',89,'Event','Nexus Tournament · 4v4','UNCONFIRMED recurring projection from the older-server biweekly Sunday cadence: two weeks after Sep. 27.','event',null,'unconfirmed'],
    ['2026-10-24',102,'Event','Server Tournament · Nexus qualifier','UNCONFIRMED recurring projection. If the biweekly Nexus cadence continues unchanged, the qualifying server Tournament should be the preceding Saturday, Oct. 24.','event',null,'unconfirmed'],
    ['2026-10-25',103,'Event','Nexus Tournament · 4v4','UNCONFIRMED recurring projection from the older-server biweekly Sunday cadence: two weeks after Oct. 11 and likely the final S2 Nexus before the projected Nov. 5 rollover.','event',null,'unconfirmed'],"""

new_block="""    ['2026-09-05',53,'Event','Server Tournament','CONFIRMED FOR CHARMING GLANCE from the in-game Tournament screen captured Sep. 2 at about 8:00 AM PDT: registration begins at the Sep. 4 6:00 AM PDT reset, and the user confirmed registration opens one day before the non-Nexus tournament. The timeline therefore shows the actual Server Tournament on Sat Sep. 5 rather than the registration day, keeping it clearly distinct from Nexus Tournament.','event'],
    ['2026-09-12',60,'Event','Nexus Tournament · 4v4','CONFIRMED FOR CHARMING GLANCE from the in-game Nexus screen captured Sep. 2 at about 8:00 AM PDT: “Starts in 10d 12h,” placing the start at about Sat Sep. 12, 8:00 PM PDT. This supersedes the older-server Sunday projection. Top-4 qualification format remains community-corroborated; prediction/bracket subphase timing should still be checked in game.','event'],
    ['2026-09-26',74,'Event','Nexus Tournament · 4v4','PROJECTED from the now-confirmed Sep. 12 Charming Glance Nexus plus the previously corroborated 14-day older-server cadence. If the cadence holds, the next Nexus should be Sep. 26; exact start time remains unconfirmed until an in-game countdown appears.','event',null,'unconfirmed'],
    ['2026-10-10',88,'Event','Nexus Tournament · 4v4','PROJECTED from the confirmed Sep. 12 Charming Glance Nexus and the corroborated 14-day cadence. If unchanged, the next cycle should land Oct. 10; exact start time remains unconfirmed.','event',null,'unconfirmed'],
    ['2026-10-24',102,'Event','Nexus Tournament · 4v4','PROJECTED from the confirmed Sep. 12 Charming Glance Nexus and the corroborated 14-day cadence. If unchanged, this cycle should land Oct. 24 and is likely the final S2 Nexus before the projected Nov. 5 rollover; exact start time remains unconfirmed.','event',null,'unconfirmed'],"""

if old_block not in s:
    raise SystemExit('expected old Tournament/Nexus timeline block not found')

s=s.replace(old_block,new_block,1)
p.write_text(s,encoding='utf-8')
print('Confirmed Charming Glance Tournament registration and Nexus timing from in-game countdowns')
